config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :articles
  root 'welcome#index'
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 20 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

#GET /articles
  def index
    @articles = Article.all
  end
#GET /articles/:id
  def show
    @article = Article.find(params[:id])
  end

  #GET /articles/edit/:id
  def edit
    @article = Article.find(params[:id])
  end
    #
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  #DELETE /articles/:id
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

#GET /articles/new
  def new
    @article = Article.new
  end

#POST /articles
  def create
    @article = Article.new(title: params[:article][:title], body: params[:article][:body])

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

 private
    def article_params
      params.require(:article).permit(:title,:body)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<% name  ||= "Crear"%> 
<div class="form-holder">

<h1><%= name %> Articulo</h1>

<%= form_for(@article) do |f| %>
  <% @article.errors.full_messages.each do |message|%>

      <div class="be-red white large-padding top-space">
        <%= message %>
      </div>
  <%end%>
    <div class="field">
      <%= f.text_field :title, placeholder: "Titulo", class: "form-control" %>
    </div>
    <div class="field">
      <%= f.text_area :body, placeholder: "Descripcion", style:"height:250px;", class: "form-control" %>
    </div>
    <div class="field">
      <%= f.submit "Guardar", class: "btn be-red white large-padding" %>
    </div>

<% end %>

</div>

app/views/articles/edit.html.erb
<%= render "form", name: "Editar" %>

app/views/articles/index.html.erb
<% @articles.each do |article|%>

<h1><%= link_to article.title, article %></h1>
<p><%= article.body %> - <%= link_to "Eliminar", article, method: :delete %></p>

<% end %>

app/views/articles/new.html.erb
<%= render "form" %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>
<div><%= link_to "Editar", edit_article_path(@article)%></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <header>
    <%= render "partials/navigation" %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/partials/_navigation.html.erb
<nav class="be-red white ">
  <ul class="no-list row center-xs middle-xs large-padding no-margin">
    <li class="col-md" >
      <h1 class="no-margin">Brand</h1>
    </li>
    <li class="col-md">
      <%= link_to "Inicio", root_path %>
    </li>
    <li class="col-md">
      Diseño
    </li>
    <li class="col-md">
      Tecnologia
    </li>
  <% if user_signed_in? %>
    <li class="col-md">
      <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete%>
    </li>
  <% end %>
  </ul>
</nav>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>